#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('💬 Adding PR comment with metrics...');

async function commentOnPR() {
  try {
    const resultsPath = path.join(__dirname, '../reports/analysis-results.json');
    
    if (!fs.existsSync(resultsPath)) {
      console.log('⚠️ No analysis results found, skipping PR comment');
      return;
    }
    
    const results = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
    const prNumber = process.env.PR_NUMBER;
    
    if (!prNumber) {
      console.log('⚠️ No PR number found, skipping PR comment');
      return;
    }
    
    // Generate comment content
    const comment = generateCommentContent(results);
    
    // Use GitHub API to post comment (simplified version)
    console.log('PR Comment Content:');
    console.log('='.repeat(50));
    console.log(comment);
    console.log('='.repeat(50));
    
    console.log('✅ PR comment content generated');
  } catch (error) {
    console.error('❌ PR comment failed:', error.message);
  }
}

function generateCommentContent(results) {
  const { bundleSize, performance, coverage } = results;
  
  return `## 📊 CI/CD Symphony Analysis Results

### 📦 Bundle Analysis
- **Size**: ${bundleSize?.sizeFormatted || 'N/A'}

### ⚡ Performance Metrics
- **Performance Score**: ${performance?.scores?.performance || 'N/A'}
- **Accessibility**: ${performance?.scores?.accessibility || 'N/A'}
- **Best Practices**: ${performance?.scores?.bestPractices || 'N/A'}
- **SEO**: ${performance?.scores?.seo || 'N/A'}

### 🧪 Test Coverage
- **Lines**: ${coverage?.total?.lines?.pct || 'N/A'}%
- **Statements**: ${coverage?.total?.statements?.pct || 'N/A'}%
- **Functions**: ${coverage?.total?.functions?.pct || 'N/A'}%
- **Branches**: ${coverage?.total?.branches?.pct || 'N/A'}%

---
*🤖 This comment was automatically generated by CI/CD Symphony*`;
}

if (require.main === module) {
  commentOnPR();
}

module.exports = { commentOnPR };